version: "3.3"
services:
  trade-api:
    build: .
    restart: always
    network_mode: "host"
    privileged: true
    container_name: trade-api
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    labels:
      production_status: "testing"
    environment:
      - os=ubuntu
    volumes:
      - /root/fastmovie/trade-api:/usr/src/app